# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    api.OrganizationService:
        class: ApiBundle\Services\OrganizationService
        arguments: ["@doctrine.orm.entity_manager", "@router", "@service_container", "@session", "@request", "form.factory"]
        scope: request
        
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
